### ISSUE TITLE
Bug in "JS Assignment 4: Control Flow Continued" on repl.it

### ISSUE THREAD

**Issue by DMillstone** [LambdaSchool/Precourse#1668]
Hello, not sure if this is the right repo to submit this issue to but I am having trouble with a repl.it assignment in this section. After answering all exercises for this assignment, I clicked "run tests" and was told that I had failed all sections, including the exampleExercise even though I did not change anything for the exampleExercise. I was given the following error:
> ReferenceError: exampleExercise is not defined
    at eval (eval at n.evaluate (https://repl.it/public/replbox_lang/2.20.0/javascript.js:237:152404), <anonymous>:4:5)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290616
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)
    at e.M [as queueRunnerFactory] (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:250740)
    at e.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:245810)
    at e.fn (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:300964)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290550
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)

I reset it and tried "run tests" again without changing anything, and it said the Example Exercise was answered correctly. So I began filling in my answers again one by one, checking the "run tests" after each one. When exerciseOne and exerciseTwo are completed there is no problem, it says that both of them and the exampleExercise are all answered correctly. Once I filled out exerciseThree and/or exerciseFour I get the same error message that every exercise is answered incorrectly, including the example. Here are the other error messages:

>ReferenceError: exerciseOne is not defined
    at eval (eval at n.evaluate (https://repl.it/public/replbox_lang/2.20.0/javascript.js:237:152404), <anonymous>:9:5)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290616
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)
    at e.M [as queueRunnerFactory] (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:250740)
    at e.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:245810)
    at e.fn (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:300964)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290550
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at e (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290094)

>ReferenceError: exerciseTwo is not defined
    at eval (eval at n.evaluate (https://repl.it/public/replbox_lang/2.20.0/javascript.js:237:152404), <anonymous>:14:5)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290616
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)
    at e.M [as queueRunnerFactory] (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:250740)
    at e.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:245810)
    at e.fn (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:300964)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290550
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at e (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290094)

>ReferenceError: exerciseThree is not defined
    at eval (eval at n.evaluate (https://repl.it/public/replbox_lang/2.20.0/javascript.js:237:152404), <anonymous>:19:5)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290616
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)
    at e.M [as queueRunnerFactory] (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:250740)
    at e.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:245810)
    at e.fn (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:300964)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290550
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at e (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290094)

>ReferenceError: exerciseFour is not defined
at eval (eval at n.evaluate (https://repl.it/public/replbox_lang/2.20.0/javascript.js:237:152404), <anonymous>:24:5)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290616
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at n.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:289470)
    at e.M [as queueRunnerFactory] (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:250740)
    at e.execute (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:245810)
    at e.fn (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:300964)
    at https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290550
    at n.run (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290835)
    at e (https://repl.it/public/replbox_lang/2.20.0/javascript.js:684:290094)

**Comment by DMillstone** [comment]
Additionally I am having a similar problem on "JS Assignment 8: Scope and the Return Statement". I filled out Exercise 1 Parts I & II and Exercise 2 correctly, but when I submit the same answers with Exercise 3 completed it says all of them are wrong.

**Comment by DMillstone** [comment]
I have since been able to solve both of these problems, I think incorrect answers in one of the exercises caused nesting errors in all of the other exercises. Feel free to close this issue if it's not a big deal. I do think it would be helpful to other precourse students if these individual exercises were self-contained. Also apologies if I'm using any inaccurate nomenclature as I am fairly new at this myself.
Thank you.
